In [1]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten
from keras.layers import Conv2D,MaxPooling2D,Dropout,BatchNormalization

model=Sequential()
model.add(Conv2D(256,(3,3),input_shape=[224,224,1],kernel_initializer='orthogonal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(128,(3,3),kernel_initializer='orthogonal'))
#model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,(3,3)))
#model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(32,activation='relu'))
model.add(Dense(2,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

2022-10-27 05:37:46.497289: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-27 05:37:47.019946: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-27 05:37:47.020000: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-27 05:37:47.101205: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-27 05:37:48.275456: W tensorflow/stream_executor/platform/de

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 256)     2560      
                                                                 
 batch_normalization (BatchN  (None, 222, 222, 256)    1024      
 ormalization)                                                   
                                                                 
 activation (Activation)     (None, 222, 222, 256)     0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 111, 111, 256)    0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 109, 109, 128)     295040    
                                                                 
 activation_1 (Activation)   (None, 109, 109, 128)     0

2022-10-27 05:37:49.555759: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-10-27 05:37:49.555776: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DMNS): /proc/driver/nvidia/version does not exist
2022-10-27 05:37:49.556632: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
model.load_weights('CNNM422.h5')

In [ ]:
import os
import cv2
import numpy as np

test_path='Resize_Patient_testing'
img_names=os.listdir(test_path)
category_dict={0:'Normal',1:'Patient'}

for img_name in img_names:
    img=cv2.imread(os.path.join(test_path,img_name))
    
    h,w=img.shape[0:2] #height and width eka

     #preprocessing (As done for the training images)
    #test_img=cv2.resize(img,(224,224))
    #test_img=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
    #test_img=test_img/255
    #test_img=test_img.reshape(1,224,224,1) #neural netowrk eka 4d input ekak illna nisa 4d krgnnwa image eka. 
    #mul tyna 1 thmi 1 image ekak nisa. multiple image tbba nam aulk na 1k image ekk nisa manually denwa.
    
    
    
    #img=cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

            # blur
    blur = cv2.GaussianBlur(gray, (0,0), sigmaX=33, sigmaY=33)

            # divide
    divide = cv2.divide(gray, blur, scale=255)

            # otsu threshold
    thresh = cv2.threshold(divide, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)[1]

            # apply morphology
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
    morph = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)

    test_img=cv2.resize(thresh,(224,224))
    test_img=test_img/255
    test_img=test_img.reshape(1,224,224,1)
    
    
    
    
    
    
    results=model.predict(test_img)
    label=np.argmax(results,axis=1)[0] #probability 2d array eken wedi eka gnnwa.
    acc=int(np.max(results,axis=1)[0]*100)
    
    print(results,label,category_dict[label],acc) 
    
    img[0:50,0:w]=[0,255,0]
    cv2.putText(img,category_dict[label],(20,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    cv2.putText(img,str(acc)+'%',(120,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    
    cv2.imshow('LIVE',img)
    k=cv2.waitKey(300)
    if(k==27):
        break
cv2.destroyAllWindows()
    

1/1 [==============================] - 0s 265ms/step
[[0.0019482  0.99805176]] 1 Patient 99


QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread (0x7a85b50).
Cannot move to target thread (0x7b954f0)

QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread (0x7a85b50).
Cannot move to target thread (0x7b954f0)

QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread (0x7a85b50).
Cannot move to target thread (0x7b954f0)

QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread (0x7a85b50).
Cannot move to target thread (0x7b954f0)

QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread (0x7a85b50).
Cannot move to target thread (0x7b954f0)

QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread (0x7a85b50).
Cannot move to target thread (0x7b954f0)

QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread (0x7a85b50).
Cannot move to target thread (0x7b954f0)

QObject::moveToThread: Current thread (0x7b954f0) is not the object's thread

1/1 [==============================] - 0s 68ms/step
[[0.00137646 0.9986235 ]] 1 Patient 99
1/1 [==============================] - 0s 69ms/step
[[0.01124998 0.98875004]] 1 Patient 98
1/1 [==============================] - 0s 91ms/step
[[0.02295296 0.977047  ]] 1 Patient 97
1/1 [==============================] - 0s 72ms/step
[[0.00634845 0.9936515 ]] 1 Patient 99
1/1 [==============================] - 0s 98ms/step
[[0.05760966 0.94239026]] 1 Patient 94
1/1 [==============================] - 0s 81ms/step
[[0.00662804 0.99337196]] 1 Patient 99
1/1 [==============================] - 0s 101ms/step
[[0.00980895 0.990191  ]] 1 Patient 99
1/1 [==============================] - 0s 64ms/step
[[0.04271033 0.9572897 ]] 1 Patient 95
1/1 [==============================] - 0s 96ms/step
[[2.7027279e-06 9.9999726e-01]] 1 Patient 99
1/1 [==============================] - 0s 85ms/step
[[0.08519254 0.9148075 ]] 1 Patient 91
1/1 [==============================] - 0s 77ms/step
[[3.7992405e-04 9.9962008e-01]]